---
- hosts: uat1
  become: true

  vars_files:
    - vars.yml
  
  pre_tasks:
    - name: Update apt cache if required
      apt: 
        update_cache: true
        cache_valid_time: 3000

  handlers:
    - name: Restart solr services
      service:
        name: solr
        state: restarted
  tasks:
    - name: Install java
      apt:
        name: openjdk-8-jdk
        state: present
    - name: Downlaod solr
      get_url:
        url: "https://mirrors.ocf.berkeley.edu/apache/solr/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"
    - name: Expand solr.
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ solr_dir }}"
        remote_src: true
        creates: "{{ solr_dir }}/solr-{{ solr_version }}/README.md"
    - name: Run Solr installation script.
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /home/macko/app/
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{ solr_dir }}/bin/solr
    - name: Ensure solr is started and enabled at boot
      service:
        name: solr
        state: started
        enabled: yes