- name: Ansible Copy Example Local to Remote
  hosts: all
  become: true
  tasks:
    - copy:
        src: $HOME/pfetch-master/pfetch
        dest: /etc/profile.d/pfetch
        owner: root
        group: root
        mode: 0f755
        remote_src: true
